server.name: kibana
server.host: 0.0.0.0
server.basePath: "/monitoring"
server.rewriteBasePath: true
server.publicBaseUrl: "http://localhost:5601/monitoring"
monitoring.ui.container.elasticsearch.enabled: true # Для корректного сбора метрик с elastic search, запущенного в контейнере

elasticsearch.hosts: [ "http://elasticsearch:9200" ]
