global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

    metric_relabel_configs:
      - source_labels: [container]
        regex: ^(api_gateway_service|order_service)$
        target_label: keep
        replacement: "yes"
        action: replace

      - source_labels: [name]
        regex: .*/?(api_gateway_service|order_service)$
        target_label: keep
        replacement: "yes"
        action: replace

      - source_labels: [keep]
        regex: ^yes$
        action: keep

      - source_labels: [container]
        regex: ^(.+)$
        target_label: service
        action: replace

      - regex: ^keep$
        action: labeldrop
